# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-26 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actsapi', '0002_auto_20211225_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('property', 'schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([]),
        ),
    ]
