# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actsapi', '0005_auto_20211226_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
